### PR TITLE
Delete LICENSE

### PR DESCRIPTION
**Pull request by amiiiiii830**

### CODE REVIEW

**Comment by jaykchen** [comment]
lgtm

**Comment by amiiiiii830** [comment]
lgtm too

**Comment by jaykchen** [comment]
lgtm

**Review by jaykchen — COMMENTED** [review]
lgtm

**Comment by amiiiiii830** [comment]
my comment lgtm

**Comment by amiiiiii830** [comment]
I mean some parting remarks

**Pull request closed without merging**
